version: "3.9"
services:
  app:
    container_name: app-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev} # override to use dev stage
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
    ports:
      - 8080:8080
