version: "3.9"
services:
  app:
    container_name: "{{ cookiecutter.__project_slug }}"
    build:
      context: ../
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev} # override to use dev stage
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
